#my school
print ("Please fill in this form below")
school = input ("What is the name of your school? ")
print ("The name of your school is " + school)
print ("What is the name of your teacher? ")
teacher = input ("What is the name of your teacher? ")
print ("The name of your teacher is " + teacher)
print ("What is your favorite subject? ")
subject = input ("What is your favorite subject? ")
print ("Your favorite subject is " + subject)
print ("What is your least favorite subject? ")
least = input ("What is your least favorite subject? ")
print ("Your least favorite subject is " + least)
print ("What is your grade? ")
grade = input ("What is your grade? ")
print ("Your grade is " + grade)
print ("What is your favorite thing about school? ")
favorite = input ("What is your favorite thing about school? ")
print ("Your favorite thing about school is " + favorite)
print ("What is your least favorite thing about school? ")
leastfavorite = input ("What is your least favorite thing about school? ")
print ("Your least favorite thing about school is " + leastfavorite)
print ("Thank you a lot for filling out the form!")